export { default as Hero } from './hero'
export { default as WhatsJumpServer } from './whats-jumpserver'
export { default as Advantages } from './advantages'
export { default as XPack } from './x-pack'
export { default as Support } from './support'
export { default as Edition } from './edition'
export { default as ContactUs } from './contact-us'
